CREATE TABLE ad_group (
      id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
      ad_group_id BIGINT NOT NULL DEFAULT 0 COMMENT '广告组ID',
      budget_mode VARCHAR(255) NOT NULL DEFAULT '' COMMENT '预算模式',
      create_date VARCHAR(255) NOT NULL DEFAULT '' COMMENT '创建日期',
      marketing_goal VARCHAR(255) NOT NULL DEFAULT '' COMMENT '营销目标',
      marketing_scene VARCHAR(255) NOT NULL DEFAULT '' COMMENT '营销场景',
      name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
      status VARCHAR(255) NOT NULL DEFAULT '' COMMENT '状态',
      budget DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '预算',


      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
      deleted_at DATETIME(3) NULL DEFAULT NULL COMMENT '删除时间',

      UNIQUE KEY (ad_group_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT='广告组表';