CREATE TABLE users (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
   username VARCHAR(50) UNIQUE NOT NULL COMMENT '用户名',
   passwd VARCHAR(255) NOT NULL COMMENT '密码',
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户表';

