apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-boost
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ad-boost
  template:
    metadata:
      labels:
        app: ad-boost
    spec:
      containers:
        - name: ad-boost
          image: registry.ap-southeast-1.aliyuncs.com/pdfgpt/boost:v0.0.1
          ports:
            - containerPort: 9000
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - mountPath: "/opt/output/log"
              subPath: "log"
              name: log-storage
      imagePullSecrets:
        - name: aliyun-secret
      volumes:
        - name: log-storage
          persistentVolumeClaim:
            claimName: log-pvc