apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    stop-writes-on-bgsave-error no
    requirepass myredistaimer231
    user taimer on >myredistaimer231 +@all